### ISSUE TITLE
Can you please add a compiled version?

### ISSUE THREAD

**Issue by ilkekaratas** [starshinata/PS4-Keyboard-and-Mouse-Adapter#1]
Title. Can you add a compiled version too? I don't know how to compile :(

**Comment by starshinata** [comment]
Sorry for the trouble, guys! I marked the repository as public a bit too early, didn't expect anyone to stumble upon it. I'm working on the installer. Will publish a release in a few hours!

**Comment by starshinata** [comment]
Released! Go to the main page to find the download link.
