### ISSUE TITLE
Whislist

### ISSUE THREAD

**Issue by sedat8879** [starshinata/PS4-Keyboard-and-Mouse-Adapter#10]
Hi bro ı loved your program PS4 Keyboard and Mouse Adapter v1.0.7.
Can you add default settings button for mouse setting. ı changed sometings to play fps games but ı forget what was the default setting of mouse :(

**Comment by pancakeslp** [comment]
Try 1.0.11 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/1.0.11 

Closing as this should resolve the issue, but feel free to reopen.
