### ISSUE TITLE
Add mapping for Playstation symbol button

### ISSUE THREAD

**Issue by yeshua-on-wings** [starshinata/PS4-Keyboard-and-Mouse-Adapter#16]
^ Seems self-explanatory. Just starting to try out this tool, but seems quite impressive so far. Thanks!

**Comment by pancakeslp** [comment]
Try the prerelease of v1.0.9 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/1.0.9 
There are fixes in this version which address the issue

**Comment by pancakeslp** [comment]
closing as 1.0.9, and 1.0.10 have now been released with this feature
