### ISSUE TITLE
MAP MOVEMENT TO MOUSE

### ISSUE THREAD

**Issue by Drasticallly** [starshinata/PS4-Keyboard-and-Mouse-Adapter#17]
How do I switch the mouse to the left analog? I see there's a an update for it but idk how.

**Comment by pancakeslp** [comment]
Try the prerelease of v1.0.9 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/1.0.9 
There are fixes in this version which address the issue

**Comment by pancakeslp** [comment]
closing as 1.0.9, and 1.0.10 have now been released with this feature
