### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by killerofstorm** [starshinata/PS4-Keyboard-and-Mouse-Adapter#2]
i installed setup.exe 
it's fully installed without any error
but when i run it just remoteplay will open
and no keybord mapping 
whats the problem ?

**Comment by starshinata** [comment]
Hi, @killerofstorm, looks like the release version had some problems with the updater at startup. I made a new release (v1.0.2). Follow these steps to fix it:
1. Restart the application
2. Leave it running for 10-15 seconds
3. Quit the application
4. Run it again
Now you should automatically get the new version. Do this and don't forget to tell me if it works. You will know your version is updated if the window title says v1.0.2 on it, like this:
![v1 0 2](https://user-images.githubusercontent.com/52502823/78999396-6aea0100-7b42-11ea-9c8c-ea0b313b1d45.png)

Sorry for the trouble! I wasn't expecting anyone to use this program. Tell me how it goes and feel free to mention any other problems that you come across so I can fix them 👍 .

**Comment by killerofstorm** [comment]
i did your steps
nothing happen
remote play automatic started up
but never saw this:
![](https://user-images.githubusercontent.com/52502823/78999396-6aea0100-7b42-11ea-9c8c-ea0b313b1d45.png)
when i use EasyHook64Svc.exe it show this error"
---------------------------
Windows Service Start Failure
---------------------------
Cannot start service from the command line or a debugger.  A Windows Service must first be installed (using installutil.exe) and then started with the ServerExplorer, Windows Services Administrative tool or the NET START command.
---------------------------
OK   
---------------------------
i use updater.exe and it makes PS4KeyboardAndMouseAdapter-1.0.2-delta.nupkg with 0 kb size

**Comment by killerofstorm** [comment]
i fully updated to 1.0.2 with your release 
but nothing happen just it starts remote play and nothing

**Comment by starshinata** [comment]
@killerofstorm Interesting. Let's continue on chat so I can fix this quicker. My username on Discord is b58#0183. Can you add me there?

**Comment by starshinata** [comment]
Fixed. Turned out he had a patched RemotePlay, so he had to reinstall it. If you end up having the same problem, you need to manually delete the RemotePlay folder (in program files). Uninstalling through Control Panel won't work.
