### ISSUE TITLE
PS4 Remote Play Update

### ISSUE THREAD

**Issue by ahmedkashif69** [starshinata/PS4-Keyboard-and-Mouse-Adapter#22]
Hey man, I love Your work. Ive been using it for like 4 months and im in love with it but 3 days ago psn updated remote play and now the ps4 mouse and keyboard application is glitched where it says update remote play but i already have it updated. It just crashes when i click on update. I managed to run it somehow, I have no idea how but now its not working. Please update the software.
-Thanks

**Comment by keeganostrowski** [comment]
(Recommented)

So I'm not sure if this fix only worked for me, but hopefully it works for you too.

Step 1: UNINSTALL your current PS Remote Play

Step 2: REINSTALL

Step 3: When reinstalling, make sure when it asks you 
"Install PS Remote Play to:
C:\Program Files (x86)\Sony\PS Remote Play"
That you change
"C:\Program Files (x86)\Sony\PS Remote Play"
To
"C:\Program Files (x86)\PS4 Remote Play"
(MUST REMOVE "\Sony" AND MUST ADD A "4" TO "PS")

![image](https://user-images.githubusercontent.com/73199067/96643260-29e65c80-12dc-11eb-8ff6-7cedd8b63bfa.png)

![image](https://user-images.githubusercontent.com/73199067/96643281-336fc480-12dc-11eb-9986-153b038a08e8.png)

![image](https://user-images.githubusercontent.com/73199067/96643299-38347880-12dc-11eb-8cb5-2c19f31053d7.png)

Step 4: Start PS4Keyboard&MouseAdapter

Step 5: Profit???

![image](https://user-images.githubusercontent.com/73199067/96643400-5bf7be80-12dc-11eb-9154-334082cd888c.png)

It was that simple for me.

Now I can play Bloodborne with my Guitar Hero controller on stream via PS Remote Play.

**Comment by pancakeslp** [comment]
Closing issue as have released PS4-Keyboard-and-Mouse-Adapter v1.0.8 which with updated paths to new Sony Remote play client.
Please reopen if you are experiencing issue on v1.0.8
