### ISSUE TITLE
PS button not mapped

### ISSUE THREAD

**Issue by guestofhonor** [starshinata/PS4-Keyboard-and-Mouse-Adapter#25]
Thanks for the amazing work you've done but the PS and Share buttons are not mapped.

Regards

**Comment by pancakeslp** [comment]
Come back in a few days (maybe a week if you are unlucky)
Ive got a new version coming which should address this.

**Comment by guestofhonor** [comment]
Thanks a lot

**Comment by pancakeslp** [comment]
Try the prerelease of v1.0.9 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/1.0.9 
There are fixes in thie version which address this issue

**Comment by pancakeslp** [comment]
closing as 1.0.9, and 1.0.10 have now been released with this feature
