### ISSUE TITLE
BSOD on open

### ISSUE THREAD

**Issue by DavidMartins00** [starshinata/PS4-Keyboard-and-Mouse-Adapter#28]
When i open the "PS4KeyboardAndMouseAdapter.exe" it show remote play for a few seconds and then make the computer blue screen with "service exeption" message

**Comment by pancakeslp** [comment]
any pictures or logs ?

**Comment by DavidMartins00** [comment]
1.0.8
No I can’t take a picture, it just blue screen few seconds after open remote play
But if I open remote play without the adapter exe it works fine

**Comment by pancakeslp** [comment]
Kinda need more information
Not sure what I need, as this is the first BSOD reported, lets start with 
* could you make a note of the error number from the BSOD (and is it consistent for every BSOD)?
* what is the operating system - eg windows 10, windows xp?
* is there anything in the event manager just as you start the adapter?
* is there a log at C:\Users\pancakes\AppData\Local\PS4KeyboardAndMouseAdapter\app-1.0.8\logs\log.txt (if there is feel free to attach it to this issue)

**Comment by DavidMartins00** [comment]
Here is a video I recorded https://imgur.com/gallery/VCJyDDR
And have some errors during the installation related to EasyHookSvc
![Uploading 9DF67DD5-C880-4A9D-BA02-BBE0F1730FA3.png…]()

**Comment by DavidMartins00** [comment]
> Kinda need more information
> Not sure what I need, as this is the first BSOD reported, lets start with
> 
> * could you make a note of the error number from the BSOD (and is it consistent for every BSOD)?
> * what is the operating system - eg windows 10, windows xp?
> * is there anything in the event manager just as you start the adapter?
> * is there a log at C:\Users\pancakes\AppData\Local\PS4KeyboardAndMouseAdapter\app-1.0.8\logs\log.txt (if there is feel free to attach it to this issue)

Win10

BSOD give "System Service Exception" , all times

I tried to install 1.0.9, the log is 
"52020-11-19 23:04:06.331 +00:00 [INF] Log created
2020-11-19 23:04:32.458 +00:00 [ERR] RemotePlay not found in list of processes
2020-11-19 23:07:16.394 +00:00 [INF] Log created
2020-11-19 23:07:32.540 +00:00 [ERR] RemotePlay not found in list of processes
2020-11-19 23:08:49.872 +00:00 [INF] Log created
2020-11-19 23:09:01.726 +00:00 [ERR] RemotePlay not found in list of processes
2020-11-19 23:11:53.417 +00:00 [INF] Log created
2020-11-19 23:12:11.578 +00:00 [INF] Log created"

**Comment by pancakeslp** [comment]
I've generated a release with extra logging at https://github.com/pancakeslp/PS4-Keyboard-and-Mouse-Adapter/releases/tag/bsod-with-extra-logging

I would appreciate if you could try this build, and share the output of the log
cause it is a different version log will be at  C:\Users\pancakes\AppData\Local\PS4KeyboardAndMouseAdapter\app-1.0.10\logs\log.txt

**Comment by DavidMartins00** [comment]
Well it BSOD on instalation i think is EasyHookSvc problem

**Comment by DavidMartins00** [comment]
Tried to open, nothing shows up, log:
"
2020-11-20 01:52:33.761 +00:00 [INF] Log created
2020-11-20 01:52:33.855 +00:00 [INF] App.UpdateIfAvailable() start
2020-11-20 01:52:33.855 +00:00 [INF] App.UpdateIfAvailable() trying GitHubUpdateManager
2020-11-20 01:52:35.089 +00:00 [INF] MainWindowView constructor IN
2020-11-20 01:52:35.292 +00:00 [INF] MainViewModel constructor IN
2020-11-20 01:52:42.493 +00:00 [INF] InjectionInterface for 20-11-20 01:52:39 made
2020-11-20 01:52:42.500 +00:00 [INF] Hooks.Run IN
2020-11-20 01:52:42.505 +00:00 [INF] OnInjectionSuccess clientPID 5520
2020-11-20 01:52:42.511 +00:00 [INF] MainViewModel constructor OUT
2020-11-20 01:52:42.516 +00:00 [INF] Hooks.DotNetHooks IN
"

**Comment by DavidMartins00** [comment]
On installation still gives this error https://imgur.com/gallery/cILtBqe cloud be app not installing correctly?

**Comment by pancakeslp** [comment]
I've spent a non trivial amount of time reviewing the code that relates to easy hook.
As I understand it those installation errors are currently expected. I'm 99% sure that we can remove those error messages in a subsequent release.

All I can offer ATM is suggesting your event manager again
If you start the app, BSOD, then run the below 3 commands, and share their output, we may get something (since i don't know what you have installed you may want to DM those instead of posting them publically) 
```
wevtutil qe Application /c:100 /rd
wevtutil qe SECURITY  /c:100 /rd
wevtutil qe SYSTEM  /c:100 /rd
```

Then the generic BSOD advice of run
` chkdsk c: /f `  and  `  sfc /scannow  `

Sorry

**Comment by DavidMartins00** [comment]
Where u want me to dm you? Can u provide the email?

**Comment by pancakeslp** [comment]
My email is pancakeslp@gmail.com

**Comment by pancakeslp** [comment]
David have replied to your email

Also for anyone I forgot to mention the DISM tool, that can help repairing some stuff
https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by pancakeslp** [comment]
Closing as David reports this is no longer a problem as of v2.0.0

For reference David is TheStalker#6353 on discord
