### ISSUE TITLE
Rebind Mouse Buttons [Feature Request]

### ISSUE THREAD

**Issue by spigelli** [starshinata/PS4-Keyboard-and-Mouse-Adapter#29]
Not sure how difficult adding a mouse listener when recording a bind would be, but this would be nice for games like spider-man where attack is square.

**Comment by pancakeslp** [comment]
its on the todo list (no eta sorry)

**Comment by pancakeslp** [comment]
Try  v2.0.0 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/2.0.0
Both suggestions are included in this version

Closing issue, as this should be resolved
