### ISSUE TITLE
Issue with Remote Play

### ISSUE THREAD

**Issue by Gabbo199** [starshinata/PS4-Keyboard-and-Mouse-Adapter#3]
Hi, first of all I wanted to congratulate you for creating this program, secondly I wanted to report a bug that doesn't start the application. After installing the official Sony Remote Play app, the program continues to show the following message:
**"Remote play is required to play on PS4. Do you want to install it now?".** 
I hope it can be solved because this program would be really cool!

**Comment by starshinata** [comment]
Hi @Gabbo199, thanks! This is a known bug, it occurs when your system language is different than English, or if you haven't installed Remote Play to the default directory. I'm going to release a new version (v1.0.6) tomorrow to provide a fix specifically for this bug. :)

**Comment by Gabbo199** [comment]
Awesome! Thank you so much for the reply and keep it up with the good work! 🔝👍🏻

**Comment by Gabbo199** [comment]
I solved the problem, i just changed the System language of windows in "English" and now everything work!

**Comment by starshinata** [comment]
@Gabbo199, Wow, you solved it on your own, great job! Sorry for not delivering the update I promised yesterday, I'm having a hard time with troubleshooting some weird stuff. Don't forget to drop some feedback on whether it works well, whether there is lag, and so on :)

**Comment by Gabbo199** [comment]
Yep! :) 
I'm gonna test this and let you know ;)
