### ISSUE TITLE
"PS4 Remote Play is required"

### ISSUE THREAD

**Issue by HenriqueHff** [starshinata/PS4-Keyboard-and-Mouse-Adapter#4]
"In order to play, PS4 Remote Play is required. Do you want to install it now?"
I've tried:
1 - installing remoteplay in the default folder (I was installing it in an alternate directory)
2 - change the system language to English and reinstall remoteplay (official website) in the default folder
I also tried to uninstall the ps4 remoteplay and making sure it left no trace, after making sure the system is in english i started "setup.exe" and asked to install ps4 remote play, and then I tried to run the shortcut that was created on the desktop, but the program keeps asking to install the ps4 remote play, there is no way of the program "ask" the directory where remoteplay is installed to solve the problem?
I found the program very interesting, I already used gimx (closed code) but it requires that a control be connected to the computer and does not work with remoteplay, I think your program is very promising and with only a few minor corrections it can become a great project, bye.

**Comment by starshinata** [comment]
@HenriqueHff Thanks for the feedback. That's a weird problem. Hit me up on Discord, I need to try out some things. https://discord.gg/Ma7DMMj
