### ISSUE TITLE
《PS Remote Play》 flash back when  《PS4KeyboardAndMouseAdapter 》is turned on

### ISSUE THREAD

**Issue by GRPWD** [starshinata/PS4-Keyboard-and-Mouse-Adapter#41]
1.When starting 《PS4KeyboardAndMouseAdapter 》， 《PS Remote Play》 will start automatically, but it will cause B to flash back when connecting PS5. 
2.If《PS Remote Play》 is restarted, 《PS Remote Play》 will not flash back, but 《PS4KeyboardAndMouseAdapter 》 will be invalid.

Thank you for your support！

**Comment by pancakeslp** [comment]
"but it will cause B to flash back when connecting PS5"

pardon, can you explain that i dont understand

**Comment by GRPWD** [comment]
cant get PS4KMA + remote play to work together when used ps5
thanks

**Comment by pancakeslp** [comment]
I can't offer full support for ps5 as i dont have one.

Try reading
https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/troubleshooting.md

If error persists you cab email me the logs at
C:\Users\{USER}\AppData\Local\PS4KeyboardAndMouseAdapter\{VERSION\logs\ to
***@***.***

**Comment by GRPWD** [comment]
[log.txt](https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/files/6528184/log.txt)

**Comment by pancakeslp** [comment]
What remote play are you using, and where is it installed?

Ill send you a beta build for 2.2.0 later, its got some fixes and some
better debugging

**Comment by GRPWD** [comment]
First, I try to install it automatically from PS4KeyboardAndMouseAdapter(V2.10)，but application says "need to install remote play" although I already have it installed
Then I try installed from https://remoteplay.dl.playstation.net/remoteplay/lang/cs/ps5_win.html    (now)
Thank you again！

**Comment by pancakeslp** [comment]
So https://remoteplay.dl.playstation.net/remoteplay/lang/cs/ps5_win.html is where you got it from; I'm asking where did it get installed? I would expect to be installed at something like "C:\Program Files (x86)\Sony\PS Remote Play\RemotePlay.exe"

try 2.2.0 at https://github.com/pancakeslp/PS4-Keyboard-and-Mouse-Adapter/releases/download/2.2.0-early-2021.05.23/Setup.exe
Then email me the log at pancakeslp at gmail.com

**Comment by GRPWD** [comment]
I photographed my computer and ps5 with my mobile phone and recorded when < PS remote play &gt; would automatically turn off. At the same time, the failure of < ps4kma &gt; after manually opening < PS remote play &gt; is recorded


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starshinata/PS4-Keyboard-and-Mouse-Adapter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 上午6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starshinata/PS4-Keyboard-and-Mouse-Adapter] 《PS Remote Play》 flash back when  《PS4KeyboardAndMouseAdapter 》is turned on (#41)





 
So https://remoteplay.dl.playstation.net/remoteplay/lang/cs/ps5_win.html is where you got it from; I'm asking where did it get installed? I would expect to be installed at something like "C:\Program Files (x86)\Sony\PS Remote Play\RemotePlay.exe"
 
try 2.2.0 at https://github.com/pancakeslp/PS4-Keyboard-and-Mouse-Adapter/releases/download/2.2.0-early-2021.05.23/Setup.exe
 Then email me the log at pancakeslp at gmail.com
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 

从QQ邮箱发来的超大附件

VID_20210524_104010.mp4 (124.15M, 2021年06月23日 10:55 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7a6137337fc805cc30be587640640a1b5205065053575c571b02075502490c0206541a0b00050d1902500f07055459510e040603667338627f256801565609040353036c57540c040751195e16503809&t=exs_ftn_download&code=6a73fd84

**Comment by GRPWD** [comment]
installed in "C:\Program Files (x86)\Sony\PS Remote Play\RemotePlay.exe"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starshinata/PS4-Keyboard-and-Mouse-Adapter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 上午6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starshinata/PS4-Keyboard-and-Mouse-Adapter] 《PS Remote Play》 flash back when  《PS4KeyboardAndMouseAdapter 》is turned on (#41)





 
So https://remoteplay.dl.playstation.net/remoteplay/lang/cs/ps5_win.html is where you got it from; I'm asking where did it get installed? I would expect to be installed at something like "C:\Program Files (x86)\Sony\PS Remote Play\RemotePlay.exe"
 
try 2.2.0 at https://github.com/pancakeslp/PS4-Keyboard-and-Mouse-Adapter/releases/download/2.2.0-early-2021.05.23/Setup.exe
 Then email me the log at pancakeslp at gmail.com

**Comment by pancakeslp** [comment]
is there a log with the new version ?

**Comment by GRPWD** [comment]
YES!&nbsp;
V2.2
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starshinata/PS4-Keyboard-and-Mouse-Adapter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starshinata/PS4-Keyboard-and-Mouse-Adapter] 《PS Remote Play》 flash back when  《PS4KeyboardAndMouseAdapter 》is turned on (#41)





 
is there a log with the new version ?

**Comment by pancakeslp** [comment]
there was no log attached to your last message

**Comment by pancakeslp** [comment]
Closing due to lack of reply
