### ISSUE TITLE
failed to extract installer

### ISSUE THREAD

**Issue by 12cicfsj** [starshinata/PS4-Keyboard-and-Mouse-Adapter#47]
when i open the setup.exe , it says "installation has failed , failed to extract installer.

**Comment by pancakeslp** [comment]
Assuming you are not jannique from discord you are the second person to
notice this.
No offence to jannique i figured it was something local to their machine.

Im due to meet up with jannique later today, will update you when we have a
resolution.

**Comment by pancakeslp** [comment]
been looking into it,
do you have a log file at 
%LOCALAPPDATA%\SquirrelTemp

if so can you email the log to pancakeslp@gmail.com

also did you try running setup with anti virus turned off ?

**Comment by pancakeslp** [comment]
try https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/download/2.2.0/application-extract-me.zip

**Comment by pancakeslp** [comment]
closing due to lack of response
