### ISSUE TITLE
Wishlist:

### ISSUE THREAD

**Issue by tripleblack** [starshinata/PS4-Keyboard-and-Mouse-Adapter#5]
This is SUCH a cool thing you made bro, thank you so much for your hard work!

- ability to map mouse buttons.
- ability to stop M/KB from working on RemotePlay so user can user computer as normal without messing up the PS4.

**Comment by starshinata** [comment]
Thanks! I'll make sure to add both suggestions in the next update (v1.0.8).

**Comment by pancakeslp** [comment]
Try  v2.0.0 https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/tag/2.0.0
Both suggestions are included in this version

Closing issue, as this should be resolved
