### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by Kief5555** [starshinata/PS4-Keyboard-and-Mouse-Adapter#55]
is there mac support?

**Comment by pancakeslp** [comment]
Not yet sorry, its in pipeline but no date yet

**Comment by pancakeslp** [comment]
Just noticed we already have a Mac and Linux issue open at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/issues/18

So closing this issue in favour of the preexisting one
