### ISSUE TITLE
reWASD

### ISSUE THREAD

**Issue by jack11e** [starshinata/PS4-Keyboard-and-Mouse-Adapter#76]
### Have you read the FAQ ?
* [X] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

### You are raising an Issue, what can you generalise it as ?
* [X] Problem - something is wrong
* [ ] Enhancement suggestion - i have an idea to make something better
* [ ] Other

### What Console are you using
* [X] PS5
* [ ] PS4

### What version of PS4KMA are you using ?
(Look at the title bar, if unsure send screenshot of PS4KMA app)
3.1.0

### What emulation method are you using ?
* [ ] ViGEm and NO process injection for bottom toolbar
* [X] ViGEm and process injection for bottom toolbar *recommended*
* [ ] NO ViGEm and just process injection

### Describe your issue
It says reWASD was detected in program files

**Comment by pancakeslp** [comment]
Did you mean to close this ticket within 2 minutes of opening it ?
