### ISSUE TITLE
black screen when PS remote play opened with  PS4-Keyboard-and-Mouse-Adapter

### ISSUE THREAD

**Issue by askaine** [starshinata/PS4-Keyboard-and-Mouse-Adapter#80]
[ ] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

[ ] Problem - something is wrong

[ ] PS4

PS4KMA v3.1.0

NO ViGEm and just process injection

### Describe your issue

when i open PS4KMA it automatically opens PS remote play and when i connect to my console it shows a black screen, when i manually open PS remote play and connect to my console it works fine but because i opened it manually i cant use PS4KMA

**Comment by pancakeslp** [comment]
Tried it with just ViGEm ?

**Comment by askaine** [comment]
> Tried it with just ViGEm ?

it works now ty
