### ISSUE TITLE
Can't find path at step number 3 

### ISSUE THREAD

**Issue by Zarelto** [starshinata/PS4-Keyboard-and-Mouse-Adapter#86]
### Have you read the FAQ ?
* [yes ] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

### You are raising an Issue, what can you generalise it as ?
* [x ] Problem - something is wrong
* [ ] Enhancement suggestion - i have an idea to make something better
* [ ] Other

### What Console are you using
* [ ] PS5
* [x ] PS4

### What version of PS4KMA are you using ?
(Look at the title bar, if unsure send screenshot of PS4KMA app)
v 3.1.0

### What emulation method are you using ?
* [ ] ViGEm and NO process injection for bottom toolbar
* [ ] ViGEm and process injection for bottom toolbar *recommended*
* [ x] NO ViGEm and just process injection

### Describe your issue
Im not able to launch the remoteplay app with the adapter. If i press "check Path" at step 3 it says path does exist, but the keyboard and mouse adapter does not work. Need a solution please

**Comment by pancakeslp** [comment]
Have you tried changing the path to where you installed remote play?

**Comment by Zarelto** [comment]
How do i change the path?

**Comment by pancakeslp** [comment]
the box that says "C:\Program Files (x86)\Sony\PS Remote Play\RemotePlay.exe" is a text box you can edit<br>
or you can use the button above it which says "Set Path" which allows you to navigate to the exe

**Comment by Zarelto** [comment]
Thanks. It started up remote play now with the adapter, but now i cant use MK for some reason on the remote play app. Do you now a reason/possible fix for this?

**Comment by Zarelto** [comment]
Think i fixed it now, thanks for the guidance.
