### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by eaboys35** [starshinata/PS4-Keyboard-and-Mouse-Adapter#87]
### Have you read the FAQ ?
* [ ] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

### You are raising an Issue, what can you generalise it as ?
* [ ] Problem - something is wrong
* [ ] Enhancement suggestion - i have an idea to make something better
* [ ] Other

### What Console are you using
* [ ] PS5
* [ ] PS4

### What version of PS4KMA are you using ?
(Look at the title bar, if unsure send screenshot of PS4KMA app)

### What emulation method are you using ?
* [ ] ViGEm and NO process injection for bottom toolbar
* [ ] ViGEm and process injection for bottom toolbar *recommended*
* [ ] NO ViGEm and just process injection

**Comment by pancakeslp** [comment]
closed as user submitted the default template
