### ISSUE TITLE
conflict between pc keyboard and control

### ISSUE THREAD

**Issue by mariohenriquelopes3** [starshinata/PS4-Keyboard-and-Mouse-Adapter#92]
How connect without PC keyboard and only with keyboard mapped by adapter?

### Have you read the FAQ ?
* [x ] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

### You are raising an Issue, what can you generalise it as ?
* [ ] Problem - something is wrong
* [x ] Enhancement suggestion - i have an idea to make something better
* [ ] Other

### What Console are you using
* [ ] PS5
* [x ] PS4

**Comment by mariohenriquelopes3** [comment]
The adapter is working, but the pc keyboard too.
When I press the A key, instead of it going to the left, the character A is input. I would like to not connect the windows keyboard.
![image](https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/assets/38667463/68922b02-f1c0-4250-8023-3b81d16932fb)
![image](https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/assets/38667463/043b99e7-feff-4461-8106-78672543d0c6)

**Comment by mariohenriquelopes3** [comment]
worked with rewasd, thanks!

**Comment by pancakeslp** [comment]
so did issue 85 not fix it ?

**Comment by mariohenriquelopes3** [comment]
resolved. I used rewasd as user TawapahDev suggested.
