### ISSUE TITLE
the PS4KMA  isnt a .exe

### ISSUE THREAD

**Issue by Abodsanousy** [starshinata/PS4-Keyboard-and-Mouse-Adapter#94]
hi  ,   i've  tried  to setup  the  KMA  but the setup  file   isnt a  .exe  

it  opens the  Visual Studio instead  

and when   i  look  at the  file  type  its   a .sln   

i  hope there  is a  way   to  fix    this  issue 

![image](https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/assets/169548261/30ce4681-1a9b-44bf-9484-2c91f7936661)

**Comment by starshinata** [comment]
Hi Abodsanousy,

Click here
<https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/releases/download/3.1.0/application-setup.exe>
to
download.

Also, if you have any other questions, join the discord channel here
<https://discord.gg/zgveKtme5s>.
